### ISSUE TITLE
spells going blank

### ISSUE THREAD

**Issue by Unsuriati** [Priskip/purgatory#3]
like my add mana going to a blank 10 mana no effect. I'm using noita save scummer, so do you suppose that counts as restart with active mods? Really like the mod, especially the fresh map design

**Comment by Priskip** [comment]
I'm not familiar with the save scummer mod. I do know that game mode mods
like Nightmare, Purgatory, Conjurer, etc have a buggy nature to them when
it comes to mod restarts. This is why I have the warning when you hover
over the mod restart button that it will break Purgatory. It sounds to me
that the problem is that the mod is not being initialized properly. So the
game has a spell but the data for the spell doesn't get set and so the game
renders it blank.

Not sure if I have a fix for that. If the problem is what I described, then
that's an in-engine problem. Nolla would need to fix that...
-Priskip

**Comment by Unsuriati** [comment]
you're right, it was from the save scummer, reloading and all that. THanks
